### ISSUE TITLE
Documentation sections empty since Bootstrap redesign

### ISSUE THREAD

**Issue by timhutton** [bitfehler/xs3p#2]
In the provided example, https://bitfehler.net/xs3p/address_annotated.xsd.html the documentation sections are empty, despite documentation annotations being present in the [xsd](https://github.com/bitfehler/xs3p/blob/master/examples/address_annotated.xsd).

Previously this was working.

**Comment by bitfehler** [comment]
This was fixed by merging #1, thanks to @jmarsik
